### ISSUE TITLE
Cannot change default `.rs` syntax highlighting to Rust Enhanced

### ISSUE THREAD

**Issue by MasonRemaley** [rust-lang/sublime-rust#132] opened 2017-01-02 06:06 UTC
### Sublime Text Version
Sublime Text 3 (Build 3125)

### Rust Enhanced Version
v1.0.2

### Operating system
A good example is:
OS Name	macOS
Version	10.12.1

### Expected behavior
I expected selecting `View > Syntax > Open all with current extension as... > Rust Enhanced` while in a `.rs` file to cause all `.rs` files to be opened with the Rust Enhanced syntax highlighting instead of the built in Rust highlighting.

### Actual behavior
New files are still opened with the default highlighting, and the setting is reset upon closing the file (or viewing it from a different `.rs` file.)

This does not occur when I change the hightling to anything besides "Rust Enhanced" (e.g., I can change the highlighting on `.rs` files to XML or such without a problem, so the problem seems to be something to do with this plugin in particular.) I also noticed that when I press the build key, all of the options show up twice, I assume because I'm getting the built in version and the plugin version so it's possible I was supposed to remove the built in one somehow?

### Steps to reproduce
1. Install Rust nightly via RustUp
1. Install Sublime Text 3 (Build 3125) on macOs 10.12.1
1. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> Install Package Control
2. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> Install Rust Enhanced
3. Open a `.rs` file
4. Select `View > Syntax > Open all with current extension as... > Rust Enhanced`
5. Open another `.rs` file
6. Check which syntax is being used via `View > Syntax`

**Comment by dten** [comment] 2017-01-02 07:37
Hi @MasonRemaley that sounds odd. It's something sublime is supposed to be responsible for though.
If you're using enhanced you can disable the default one by going.
Ctrl shift p, Disable package, Rust 
This will remove all the duplication then

**Comment by MasonRemaley** [comment] 2017-01-02 17:16
That works, thanks! It could be a Sublime issue, I assume there's some kind of naming conflict between the built in version of the plugin and the current one that's causing this.

**Comment by Jayflux** [comment] 2017-01-03 11:12
@MasonRemaley  how have you installed Rust Enhanced? Through Package Control or have you checked it out into the packages folder from github?

@wbond any ideas?

**Comment by michalrud** [comment] 2017-01-12 13:00
I had the same problem. Disabling the `Rust` package doesn't solve the issue, neither does reinstallation of the plugin. I can see the `Rust` package being in `ignored_packages` in preferences.

I see that the "Syntax specific settings" for files, which are set as Rust Enhanced, still opens `Rust.sublime-settings`.

I've tried to reproduce the issue on clean configuration, and after clearing sublime configuration from `~/.config/sublime-text-3` the issue was not visible. The issue appeared again after installing the RustAutoComplete plugin, so I suppose this is a conflict between these two plugins.

I'm using Sublime build 3126

**Comment by FichteFoll** [comment] 2017-01-13 13:50
I need more details to troubleshoot this. To anyone affected, what are your installed (and ignored) packages and what does `sublime.find_resources("Rust.sublime-settings")` yield?

@Jayflux it would probably help if your syntax wasn't named `Rust.sublime-syntax`, although I think that ST uses the name defined inside the syntax pretty much everywhere.

The "multiple build system entries" can likely only be solved by ignoring the default package or modifying the default one in a way that it is never active (i.e. its `selector` never matches).

**Comment by Jayflux** [comment] 2017-01-13 14:11
@FichteFoll i would happily name it to Rust Enhanced but there's a space in the name, so im not sure what to do in that scenario, the documentation says nothing about this. (underscore? hyphen? Does it need to be the same name as the package?)

**Comment by FichteFoll** [comment] 2017-01-13 14:35
There isn't anything special about using spaces in syntax file names, afaik.

**Comment by Jayflux** [comment] 2017-01-13 14:38
ok, I will start by renaming those files to RustEnhanced

**Comment by michalrud** [comment] 2017-01-14 10:40
I have reproduced the issue mentioned here on MacOS 10.12.2, Sublime 3126; completely separate PC.

Output of `sublime.find_resources("Rust.sublime-settings")`:

```
>>> sublime.find_resources("Rust.sublime-settings")
['Packages/Rust Enhanced/Rust.sublime-settings']
```

I will try to join `##sublimetext` sooner or later to help in debugging.

**Comment by MasonRemaley** [comment] 2017-01-28 02:15
I didn't see the rest of the responses until just now--I haven't had any issues since disabling the default package, so I suspect other people are having a slightly different issue than I did. I can probably cause it to happen again by reenabling the package if it would help anyone debug.

**Comment by Jayflux** [comment] 2017-02-04 17:25
https://github.com/rust-lang/sublime-rust/releases/tag/v1.1.0 *should* fix this, lets see

**Comment by Jayflux** [comment] 2017-02-24 11:32
I'm going to close this issue since it no longer seems to be a problem

**Closed by Jayflux** 2017-02-24 11:32 UTC
