### ISSUE TITLE
syntax checking fails (silently) when cargo is not in default path

### ISSUE THREAD

**Issue by conundrumer** [rust-lang/sublime-rust#126] opened 2016-11-26 09:47 UTC
SyntaxCheckPlugin was not able to find cargo, but doesn't report not being able to find it, because the actual error message is `/bin/sh: cargo: command not found`, whereas [the error checker looks for "error"](https://github.com/rust-lang/sublime-rust/blob/fb8fa9eaadfa11ee1f28d0a5ec615feb110272b8/SyntaxCheckPlugin.py#L30-L32).

I installed Rust through rustup, so cargo is in `$HOME/.cargo/bin`. But the path of SyntaxCheckPlugin is the default: `/usr/bin:/bin:/usr/sbin:/sbin`. #92 did not address this plugin.

**Comment by Jayflux** [comment] 2016-11-26 14:08
@conundrumer interesting, we don't hardcode the path, so looks like the script isn't picking up the system path

**Comment by dten** [comment] 2016-11-26 16:36
Seems we do set the path but _only_ on OSX https://github.com/rust-lang/sublime-rust/blob/master/Cargo.sublime-build#L8
So I guess everyone on OSX build would work without changes but syntax check won't. Everybody else has to have cargo on the path beforehand.

**Comment by Jayflux** [comment] 2016-11-27 16:48
@conundrumer what OS are you running this on?

**Comment by conundrumer** [comment] 2016-11-27 23:24
@Jayflux this is on OSX. I will also note that the path to `$HOME/.cargo/bin` is set on my .bashrc. Also, the build commands work.

**Comment by Jayflux** [comment] 2016-11-28 12:43
I will run a couple of tests on my macbook and windows 10 later on, and see what the problem is.
Sounds like the script isn't seeing the outer path

**Comment by jcagpir** [comment] 2016-11-28 16:42
I have the same problem with Manjaro (ArchLinux based).
My shell path is : ".../usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/lib32/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin:/home/jcag/.cargo/bin"

"/home/jcag/.cargo/bin" is Cargo installation path, but when I try to build a rust file Sublime Text doesn't get the right value of the shell path and I get the message : 
"[Errno 2] No such file or directory: 'cargo'"
...
"[path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/lib32/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin]"

**Comment by Jayflux** [comment] 2016-11-28 17:07
@wbond is it possible to get the user's env variables into the context of a sublime plugin?

**Comment by wbond** [comment] 2016-11-28 17:11
This only occurs on OS X because all applications are launched from the dock, which does not execute your shell, and thus does not have the same environment.

There is an enhancement that will be part of the next dev build that executes the user's default shell as a login shell and fetches their environment variables to get around this limitation of OS X.

**Comment by jcagpir** [comment] 2016-11-29 15:13
@wbond 
It seems it occurs in Linux manjaro too. Here is the whole error message when I try to build "guessing_game" project:

"[Errno 2] No such file or directory: 'cargo'
[cmd: ['cargo', 'run']                                       // **not "shell_cmd"**
[dir: /home/jcag/Rust/Projects/guessing_game/src]
[path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/lib32/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin]
[Finished]"

But my shell path is : 

".../usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/lib32/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin:**/home/jcag/.cargo/bin**"

and "/home/jcag/.cargo/bin" is my Cargo installation path. 
Sublime Text (Build 3126) is launched from the application menu  and Rust Enhanced plugin was installed by Package Control.
What can I do ? Thanks in advance.

**Comment by wbond** [comment] 2016-11-29 15:25
@jcagpir That means that your env for your DE isn't set properly. It isn't really up to Sublime Text to manage that for you. In fact, it seems you've gotten your env set properly for Go, Java and Perl. You just need to configure Rust also.

We are adding the work-around for OS X since there isn't really a reasonable way to set the environment of the Dock process. There were some changes that worked on some versions of OS X, but it didn't work in many situations.

**Comment by jcagpir** [comment] 2016-11-29 16:38
@wbond Thanks for your answer. 
Path env variable must be configured into "home/_UserName_/.bash_profile" file an not in "home/_UserName_/.bashrc". It consists in adding the line "export PATH=$PATH:/home/_UserName_/.cargo/bin"

**Comment by Jayflux** [comment] 2017-02-24 11:30
@conundrumer  @jcagpir is this still a problem on the latest release?

**Comment by Jayflux** [comment] 2017-02-26 12:30
@conundrumer @jcagpir did the fix in https://github.com/rust-lang/sublime-rust/pull/97 not address your issue?

**Comment by Jayflux** [comment] 2017-03-15 17:32
ok looks like the issue is still there....
Im wondering if we can add ~/.cargo/bin to the path before we spawn the process?

I might give it a go as an experiment

**Comment by Jayflux** [comment] 2017-03-15 20:44
Provided a fix here: https://github.com/rust-lang/sublime-rust/pull/166
Seems to work for me

**Closed** 2017-03-15 23:19 UTC
