### ISSUE TITLE
Console displays full path when building

### ISSUE THREAD

**Issue by vrinek** [rust-lang/sublime-rust#18] opened 2014-10-09 19:19 UTC
Given I have a rust source file which would emit a warning,
When I trigger the build from within Sublime,
Then the console displays the whole path for the source file.

```
/Users/kostaskarachalios/Code/Learning/Rust/for Rubyists/fizzbuzz.rs:15:13: 15:23 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
/Users/kostaskarachalios/Code/Learning/Rust/for Rubyists/fizzbuzz.rs:15         let mut answer =
                                                                                    ^~~~~~~~~~
```

On the other hand, when I do the same with rustc, it only displays the file's name.

```
fizzbuzz.rs:15:13: 15:23 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
fizzbuzz.rs:15         let mut answer =
                           ^~~~~~~~~~
```

**Comment by Jayflux** [comment] 2016-10-09 16:32
@vrinek 
Closing this as i can't reproduce this problem
Please re-open a ticket if its still happening

**Closed by Jayflux** 2016-10-09 16:32 UTC
